=== jfacorro/2012-1er-taller-de-programacion-ii/trunk/MEREditor/xml/tests/entidad-comp.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT PruebaEntidad (Entidad)>
<!ELEMENT Entidad (Nombre,TipoEntidad,Atributos,IdentificadoresInternos?,IdentificadoresExternos?)>
<!ELEMENT Atributo (Nombre,Cardinalidad,TipoAtributo,Formula?,Atributos?) >
<!ELEMENT Atributos (Atributo+)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Cardinalidad EMPTY>
<!ELEMENT TipoAtributo EMPTY>
<!ELEMENT Formula (#PCDATA)>
<!ELEMENT IdentificadoresInternos (RefAtributo+)>
<!ELEMENT IdentificadoresExternos (RefEntidad+)>
<!ELEMENT RefAtributo EMPTY>
<!ELEMENT RefEntidad EMPTY>
<!ELEMENT TipoEntidad EMPTY>

<!ATTLIST Atributo id CDATA #REQUIRED>
<!ATTLIST Entidad id CDATA #REQUIRED>
<!ATTLIST Cardinalidad min CDATA "1">
<!ATTLIST Cardinalidad max CDATA "1">
<!ATTLIST RefAtributo id CDATA #REQUIRED>
<!ATTLIST RefEntidad id CDATA #REQUIRED>
<!ATTLIST TipoEntidad tipo (MAESTRA_COSA|MAESTRA_DOMINIO|TRANSACCIONAL_HISTORICA|TRANSACCIONAL_PROGRAMADA) #REQUIRED>
<!ATTLIST TipoAtributo tipo (CARACTERIZACION|DERIVADO_COPIA|DERIVADO_CALCULO) #REQUIRED>

=== jfacorro/2012-1er-taller-de-programacion-ii/MEREditor/src/mereditor/tests/xml de prueba/entidad-comp.xml
<!DOCTYPE Modelo SYSTEM "entidad-comp.dtd">
<PruebaEntidad>
<Entidad id="1">
		<Nombre>Localidad</Nombre>
		<TipoEntidad tipo="MAESTRA_COSA"/>
		<Atributos>
			<Atributo id="1">
				<Nombre>fila</Nombre>
				<Cardinalidad min="1" max="1" />
				<TipoAtributo tipo="CARACTERIZACION" />
			</Atributo>
			<Atributo id="2">
				<Nombre>butaca</Nombre>
				<Cardinalidad min="1" max="1" />
				<TipoAtributo tipo="CARACTERIZACION" />
			</Atributo>
		</Atributos>
		<IdentificadoresInternos>
			<RefAtributo id="1" />
			<RefAtributo id="2" />
		</IdentificadoresInternos>
		<IdentificadoresExternos>
				<RefEntidad id="3" />
				<RefEntidad id="4" />
				<RefEntidad id="8" />
		</IdentificadoresExternos>
</Entidad>
</PruebaEntidad>
