=== jfacorro/2012-1er-taller-de-programacion-ii/trunk/MEREditor/src/mereditor/tests/xml de prueba/modelo-comp.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Modelo (Entidad*,Relacion*,Jerarquia*,Diagrama,Validacion)>
<!ELEMENT Entidad (Nombre,TipoEntidad,Atributos,IdentificadoresInternos?,IdentificadoresExternos?)>
<!ELEMENT Relacion (Nombre,TipoRelacion,Participantes,Atributos?)>
<!ELEMENT Jerarquia (TipoJerarquia,Generica,Derivadas)>
<!ELEMENT Diagrama (Nombre,Componentes?,Diagramas?,Validacion)>
<!ELEMENT Validacion (Observaciones) >

<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT TipoAtributo EMPTY>
<!ELEMENT TipoRelacion EMPTY>
<!ELEMENT TipoJerarquia EMPTY>
<!ELEMENT TipoEntidad EMPTY>
<!ELEMENT Atributos (Atributo+)>
<!ELEMENT Atributo (Nombre,Cardinalidad,TipoAtributo,Formula?,Atributos?) >
<!ELEMENT IdentificadoresInternos (RefAtributo+)>
<!ELEMENT IdentificadoresExternos (RefEntidad+)>
<!ELEMENT Participantes (Participante+)>
<!ELEMENT Participante (RefEntidad,Cardinalidad,Rol?)>
<!ELEMENT Formula (#PCDATA)>
<!ELEMENT Rol (#PCDATA)>
<!ELEMENT Cardinalidad EMPTY>
<!ELEMENT RefAtributo EMPTY>
<!ELEMENT RefEntidad EMPTY>
<!ELEMENT Generica (RefEntidad)>
<!ELEMENT Derivadas (RefEntidad+)>
<!ELEMENT Componentes (RefComponente+)>
<!ELEMENT Diagramas (Diagrama+)>
<!ELEMENT Observaciones (#PCDATA)>
<!ELEMENT RefComponente EMPTY>

<!ATTLIST Atributo id CDATA #REQUIRED>
<!ATTLIST Entidad id CDATA #REQUIRED>
<!ATTLIST Relacion id CDATA #REQUIRED>
<!ATTLIST Jerarquia id CDATA #REQUIRED>
<!ATTLIST Diagrama id CDATA #REQUIRED>
<!ATTLIST Validacion estado (VALIDADO|SIN_VALIDAR) #REQUIRED>
<!ATTLIST Cardinalidad min CDATA "1">
<!ATTLIST Cardinalidad max CDATA "1">
<!ATTLIST RefAtributo id CDATA #REQUIRED>
<!ATTLIST RefEntidad id CDATA #REQUIRED>
<!ATTLIST RefComponente id CDATA #REQUIRED>
<!ATTLIST TipoAtributo tipo (CARACTERIZACION|DERIVADO_COPIA|DERIVADO_CALCULO) #REQUIRED>
<!ATTLIST TipoRelacion tipo (ASOCIACION|COMPOSICION) #REQUIRED>
<!ATTLIST TipoJerarquia tipo (TOTAL_EXCLUSIVA|TOTAL_SUPERPUESTA|PARCIAL_EXCLUSIVA|PARCIAL_SUPERPUESTA) #REQUIRED>
<!ATTLIST TipoEntidad tipo (MAESTRA_COSA|MAESTRA_DOMINIO|TRANSACCIONAL_HISTORICA|TRANSACCIONAL_PROGRAMADA) #REQUIRED>

=== jfacorro/2012-1er-taller-de-programacion-ii/MEREditor/xml/diagrama-comp.xml
<!DOCTYPE note SYSTEM "modelo-comp.dtd">
<Modelo>
	<Entidad id="_0" tipo="MAESTRA_COSA">
		<Nombre />
		<Atributos>
			<Atributo id="_1" tipo="CARACTERIZACION">
				<Nombre />
				<Cardinalidad min="" max="" />
				<!-- Caracterizacion o derivado -->
				<Formula />
				<!-- Para el caso que sea compuesto -->
				<Atributos>
					<!-- 0..* -->
					<Atributo id="_2" tipo="CARACTERIZACION">
						<Nombre></Nombre>
						<Cardinalidad/>
						<!-- Misma estructura anterior -->
					</Atributo>
				</Atributos>
			</Atributo>
		</Atributos>
		<IdentificadoresInternos>
			<RefAtributo id="_1" />
		</IdentificadoresInternos>
		<IdentificadoresExternos>
			<RefEntidad id="_1" />
		</IdentificadoresExternos>
	</Entidad>
	<Relacion id="_5" tipo="ASOCIACION">
		<Nombre />
		<Participantes>
			<Participante>
				<RefEntidad id="_1" />
				<Cardinalidad min="" max="" />
				<!-- Descripcion del Rol -->
				<Rol></Rol>
			</Participante>
		</Participantes>
		<Atributos>
			<Atributo id="_3" tipo="CARACTERIZACION">
				<Nombre />
				<Cardinalidad min="" max="" />
				<!-- Caracterizacion o derivado -->
				<Formula />
				<!-- Para el caso que sea compuesto -->
				<Atributos>
					<!-- 0..* -->
					<Atributo id="_4" tipo="CARACTERIZACION">
						<Nombre />
						<Cardinalidad min="" max="" />
						<!-- Misma estructura anterior -->
					</Atributo>
				</Atributos>
			</Atributo>
		</Atributos>
	</Relacion>
	<Jerarquia id="_6" tipo="TOTAL_EXCLUSIVA">		
		<!-- 1 -->
		<Generica>
			<RefEntidad id="_1"/>
		</Generica>
		<Derivadas>
			<RefEntidad id="_2"/>
		</Derivadas>
	</Jerarquia>
	<Diagrama id="_7">
		<Nombre />
		<Componentes>
			<!-- 0..* -->
			<Componente id="_2" />
		</Componentes>
		<Diagramas>
			<!-- 0..* -->
			<Diagrama id="_8">
				<Nombre></Nombre>
				<Validacion estado="VALIDADO">
					<Observaciones />
				</Validacion>
				<!-- Misma estructura anterior -->
			</Diagrama>
		</Diagramas>
		<Validacion estado="SIN_VALIDAR">
			<Observaciones/>
		</Validacion>
	</Diagrama>
	<!-- Estado global de los diagramas -->
	<Validacion estado="SIN_VALIDAR">
		<Observaciones/>
	</Validacion> 
</Modelo>

=== jfacorro/2012-1er-taller-de-programacion-ii/MEREditor/src/mereditor/tests/xml de prueba/boleteria-comp.xml
<!DOCTYPE Modelo SYSTEM "modelo-comp.dtd"> 
<Modelo>
	<Entidad id="0">
		<Nombre>Localidad</Nombre>
		<TipoEntidad tipo="MAESTRA_COSA"/>
		<Atributos>
			<Atributo id="01">
				<Nombre>fila</Nombre>
				<Cardinalidad min="1" max="1" />
				<TipoAtributo tipo="CARACTERIZACION"/>
			</Atributo>
			<Atributo id="02">
				<Nombre>butaca</Nombre>
				<Cardinalidad min="1" max="1" />
				<TipoAtributo tipo="CARACTERIZACION"/>
			</Atributo>
		</Atributos>
		<IdentificadoresExternos>
			<RefEntidad id="2" />
		</IdentificadoresExternos>
	</Entidad>
	<Entidad id="2">
		<Nombre>SeccionSala</Nombre>
		<TipoEntidad tipo="MAESTRA_COSA"/>
		<Atributos>
			<Atributo id="24">
				<Nombre>nroSecc</Nombre>
				<Cardinalidad min="1" max="1" />
				<TipoAtributo tipo="CARACTERIZACION"/>
			</Atributo>
			<Atributo id="25">
				<Nombre>nomSecc</Nombre>
				<Cardinalidad min="1" max="1" />
				<TipoAtributo tipo="CARACTERIZACION"/>
			</Atributo>
		</Atributos>
	</Entidad>
	<Entidad id="4">
		<Nombre>Obra</Nombre>
		<TipoEntidad tipo="MAESTRA_COSA"/>
		<Atributos>
			<Atributo id="41">
				<Nombre>idObra</Nombre>
				<Cardinalidad min="1" max="1" />
				<TipoAtributo tipo="CARACTERIZACION"/>
			</Atributo>
			<Atributo id="42">
				<Nombre>titulo</Nombre>
				<Cardinalidad min="1" max="1" />
				<TipoAtributo tipo="CARACTERIZACION"/>
			</Atributo>
			<Atributo id="43">
				<Nombre>autor</Nombre>
				<Cardinalidad min="1" max="n" />
				<TipoAtributo tipo="CARACTERIZACION"/>
			</Atributo>
			<Atributo id="45">
				<Nombre>director</Nombre>
				<Cardinalidad min="1" max="n" />
				<TipoAtributo tipo="CARACTERIZACION"/>
			</Atributo>
			<Atributo id="46">
				<Nombre>genero</Nombre>
				<Cardinalidad min="1" max="1" />
				<TipoAtributo tipo="CARACTERIZACION"/>
			</Atributo>
			<Atributo id="47">
				<Nombre>nroProxFunc</Nombre>
				<Cardinalidad min="1" max="1" />
				<TipoAtributo tipo="CARACTERIZACION"/>
			</Atributo>
		</Atributos>
		<IdentificadoresInternos>
			<RefAtributo id="41" />
			<RefAtributo id="42" />
		</IdentificadoresInternos>
	</Entidad>
	<Entidad id="5">
		<Nombre>Funcion</Nombre>
		<TipoEntidad tipo="MAESTRA_COSA"/>
		<Atributos>
			<Atributo id="51">
				<Nombre>nroFunc</Nombre>
				<Cardinalidad min="1" max="1" />
				<TipoAtributo tipo="CARACTERIZACION"/>
			</Atributo>
			<Atributo id="52">
				<Nombre>fecha</Nombre>
				<Cardinalidad min="1" max="1" />
				<TipoAtributo tipo="CARACTERIZACION"/>
			</Atributo>
			<Atributo id="53">
				<Nombre>hora</Nombre>
				<Cardinalidad min="1" max="1" />
				<TipoAtributo tipo="CARACTERIZACION"/>
			</Atributo>
		</Atributos>
		<IdentificadoresInternos>
			<RefAtributo id="24" />
			<RefAtributo id="25" />
		</IdentificadoresInternos>
		<IdentificadoresExternos>
				<RefEntidad id="4" />
		</IdentificadoresExternos>
	</Entidad>
	<Relacion id="3">
		<Nombre>SL</Nombre>
		<TipoRelacion tipo="ASOCIACION"/>
		<Participantes>
			<Participante> 
				<RefEntidad id="0"/>
				<Cardinalidad min="1" max="1"/>
			</Participante> 
			<Participante>
				<RefEntidad id="2"/>
				<Cardinalidad min="1" max="n" />
			</Participante>
		</Participantes>
	</Relacion>
	<Relacion id="6">
		<Nombre>FO</Nombre>
		<TipoRelacion tipo="ASOCIACION"/>
		<Participantes> 
			<Participante>
				<RefEntidad id="4"/>
			 	<Cardinalidad min="0" max="n"/> 
			</Participante>
			<Participante>
				<RefEntidad id="5"/>
			 	<Cardinalidad min="1" max="1" />
			</Participante> 
		</Participantes>
	</Relacion>
	<Relacion id="7">
		<Nombre>VtaLoc</Nombre>
		<TipoRelacion tipo="ASOCIACION"/>
		<Participantes>
			<Participante>
				<RefEntidad id="4"/>
				<Cardinalidad min="0" max="n" />
			</Participante>
			<Participante>
			<RefEntidad id="0"/> 
			<Cardinalidad min="0" max="n" />
			</Participante>
		</Participantes>
		<Atributos>
			<Atributo id="71">
				<Nombre>tarj</Nombre>
				<Cardinalidad min="0" max="1" />
				<TipoAtributo tipo="CARACTERIZACION"/>
				<Atributos>
					<Atributo id="711">
						<Nombre>nomTarj</Nombre>
						<Cardinalidad min="1" max="1" />
						<TipoAtributo tipo="CARACTERIZACION"/>
					</Atributo>
					<Atributo id="712">
						<Nombre>bco</Nombre>
						<Cardinalidad min="1" max="1" />
						<TipoAtributo tipo="CARACTERIZACION"/>
					</Atributo>
					<Atributo id="713">
						<Nombre>nroTarj</Nombre>
						<Cardinalidad min="1" max="1" />
						<TipoAtributo tipo="CARACTERIZACION"/>
					</Atributo>
					<Atributo id="714">
						<Nombre>nroAutoriz</Nombre>
						<Cardinalidad min="1" max="1" />
						<TipoAtributo tipo="CARACTERIZACION"/>
					</Atributo>
					<Atributo id="715">
						<Nombre>cr</Nombre>
						<Cardinalidad min="0" max="1" />
						<TipoAtributo tipo="CARACTERIZACION"/>
						<Atributos>
							<Atributo id="7151">
								<Nombre>cuotas</Nombre>
								<Cardinalidad min="1" max="1" />
								<TipoAtributo tipo="CARACTERIZACION"/>
							</Atributo>
							<Atributo id="7152">
								<Nombre>int</Nombre>
								<Cardinalidad min="0" max="1" />
								<TipoAtributo tipo="CARACTERIZACION"/>
							</Atributo>
						</Atributos>
					</Atributo>
				</Atributos>
			</Atributo>
		</Atributos>
	</Relacion>
	<Diagrama id="99">
		<Nombre>BoleteriaTeatro</Nombre>
		<Componentes>
			<RefComponente id="0" />
			<RefComponente id="2" />
			<RefComponente id="3" />
			<RefComponente id="4" />
			<RefComponente id="5" />
			<RefComponente id="6" />
			<RefComponente id="7" />
		</Componentes>
		<Validacion estado="SIN_VALIDAR">
			<Observaciones/>
		</Validacion> 
	</Diagrama>
	<!-- Estado global de los diagramas -->
	<Validacion estado="SIN_VALIDAR">
		<Observaciones/>
	</Validacion> 
</Modelo>

=== jfacorro/2012-1er-taller-de-programacion-ii/MEREditor/xml/ejemplos/cartelera-comp.xml
<!DOCTYPE note SYSTEM "../modelo-comp.dtd">
<Modelo>
	<Entidad id="_1" tipo="MAESTRA_COSA">
		<Nombre>Intérprete</Nombre>
		<Atributos>
			<Atributo id="_11" tipo="CARACTERIZACION">
				<Nombre>idIntérp</Nombre>
				<Cardinalidad min="1" max="" />
			</Atributo>
			<Atributo id="_12" tipo="CARACTERIZACION">
				<Nombre>nombre</Nombre>
				<Cardinalidad min="1" max="" />
			</Atributo>
		</Atributos>
		<IdentificadoresInternos>
			<RefAtributo id="_11" />
			<RefAtributo id="_12" />
		</IdentificadoresInternos>
	</Entidad>
	<Entidad id="_2" tipo="MAESTRA_COSA">
		<Nombre>Obra</Nombre>
		<Atributos>
			<Atributo id="_21" tipo="CARACTERIZACION">
				<Nombre>idObra</Nombre>
				<Cardinalidad min="1" max="" />
			</Atributo>
			<Atributo id="_22" tipo="CARACTERIZACION">
				<Nombre>título</Nombre>
				<Cardinalidad min="1" max="" />
			</Atributo>
			<Atributo id="_23" tipo="CARACTERIZACION">
				<Nombre>director</Nombre>
				<Cardinalidad min="1" max="n" />
			</Atributo>
			<Atributo id="_24" tipo="CARACTERIZACION">
				<Nombre>autor</Nombre>
				<Cardinalidad min="1" max="n" />
			</Atributo>
			<Atributo id="_25" tipo="CARACTERIZACION">
				<Nombre>genero</Nombre>
				<Cardinalidad min="1" max="" />
			</Atributo>
			<Atributo id="_26" tipo="CARACTERIZACION">
				<Nombre>enCartel</Nombre>
				<Cardinalidad min="0" max="1" />
				<Atributos>
					<Atributo id="_261" tipo="CARACTERIZACION">
						<Nombre>desde</Nombre>
						<Cardinalidad min="1" max="1" />
					</Atributo>
					<Atributo id="_262" tipo="CARACTERIZACION">
						<Nombre>hasta</Nombre>
						<Cardinalidad min="0" max="1" />
					</Atributo>
				</Atributos>
			</Atributo>
		</Atributos>
		<IdentificadoresInternos>
			<RefAtributo id="_21" />
		</IdentificadoresInternos>
		<IdentificadoresExternos>
			<IdentificadorExterno>
				<Atributo id="2" />
				<Atributo id="3" />
			</IdentificadorExterno>
		</IdentificadoresExternos>
	</Entidad>
	<Relacion id="_3" tipo="COMPOSICION">
		<Nombre>Elenco</Nombre>
		<Participantes>
			<Participante>
				<RefEntidad id="_1" />
				<Cardinalidad min="0" max="n" />
			</Participante>
			<Participante>
				<RefEntidad id="_2" />
				<Cardinalidad min="0" max="n" />
			</Participante>
		</Participantes>
	</Relacion>
	<Diagrama id="_4">
		<Nombre>Cartelera Teatral</Nombre>
		<Componentes>
			<Componente id="_1" />
			<Componente id="_2" />
			<Componente id="_3" />
		</Componentes>
		<Validacion estado="SIN_VALIDAR">
			<Observaciones/>
		</Validacion>
	</Diagrama>
	<!-- Estado global de los diagramas -->
	<Validacion estado="SIN_VALIDAR">
		<Observaciones/>
	</Validacion> 
</Modelo>

=== jfacorro/2012-1er-taller-de-programacion-ii/trunk/MEREditor/xml/ejemplos/boleteria-comp.xml
<!DOCTYPE note SYSTEM "../modelo-comp.dtd">
<Modelo>
	<Entidad id="_1" tipo="MAESTRA_COSA">
		<Nombre>Localidad</Nombre>
		<Atributos>
			<Atributo id="_2" tipo="CARACTERIZACION">
				<Nombre>fila</Nombre>
				<Cardinalidad min="1" max="1" />
			</Atributo>
			<Atributo id="_3" tipo="CARACTERIZACION">
				<Nombre>butaca</Nombre>
				<Cardinalidad min="1" max="1" />
			</Atributo>
		</Atributos>
		<Identificadores>
			<Identificador>
				<RefEntidad idref="_5" />
			</Identificador>
		</Identificadores>
	</Entidad>
	<Entidad id="_5" tipo="MAESTRA_COSA">
		<Nombre>SeccionSala</Nombre>
		<Atributos>
			<Atributo id="_6" tipo="CARACTERIZACION">
				<Nombre>nroSecc</Nombre>
				<Cardinalidad min="1" max="1" />
			</Atributo>
			<Atributo id="_7" tipo="CARACTERIZACION">
				<Nombre>nomSecc</Nombre>
				<Cardinalidad min="1" max="1" />
			</Atributo>
		</Atributos>
		<Identificadores>
			<Identificador>
				<RefAtributo idref="_6" />
			</Identificador>
			<Identificador>
				<RefAtributo idref="_7" />
			</Identificador>
		</Identificadores>
	</Entidad>
	<Entidad id="_10" tipo="MAESTRA_COSA">
		<Nombre>Obra</Nombre>
		<Atributos>
			<Atributo id="_11" tipo="CARACTERIZACION">
				<Nombre>idObra</Nombre>
				<Cardinalidad min="1" max="1" />
			</Atributo>
			<Atributo id="_12" tipo="CARACTERIZACION">
				<Nombre>titulo</Nombre>
				<Cardinalidad min="1" max="1" />
			</Atributo>
			<Atributo id="_13" tipo="CARACTERIZACION">
				<Nombre>autor</Nombre>
				<Cardinalidad min="1" max="n" />
			</Atributo>
			<Atributo id="_14" tipo="CARACTERIZACION">
				<Nombre>director</Nombre>
				<Cardinalidad min="1" max="n" />
			</Atributo>
			<Atributo id="_15" tipo="CARACTERIZACION">
				<Nombre>genero</Nombre>
				<Cardinalidad min="1" max="1" />
			</Atributo>
			<Atributo id="_16" tipo="CARACTERIZACION">
				<Nombre>nroProxFunc</Nombre>
				<Cardinalidad min="1" max="1" />
			</Atributo>
		</Atributos>
		<Identificadores>
			<Identificador>
				<RefAtributo idref="_11" />
			</Identificador>
			<Identificador>
				<RefAtributo idref="_12" />
			</Identificador>
		</Identificadores>
	</Entidad>
	<Entidad id="_19" tipo="MAESTRA_COSA">
		<Nombre>Funcion</Nombre>
		<Atributos>
			<Atributo id="_20" tipo="CARACTERIZACION">
				<Nombre>nroFunc</Nombre>
				<Cardinalidad min="1" max="1" />
			</Atributo>
			<Atributo id="_21" tipo="CARACTERIZACION">
				<Nombre>fecha</Nombre>
				<Cardinalidad min="1" max="1" />
			</Atributo>
			<Atributo id="_22" tipo="CARACTERIZACION">
				<Nombre>hora</Nombre>
				<Cardinalidad min="1" max="1" />
			</Atributo>
		</Atributos>
		<Identificadores>
			<Identificador>
				<RefEntidad idref="_10" />
			</Identificador>
		</Identificadores>
	</Entidad>
	<Relacion id="_24" tipo="ASOCIACION">
		<Nombre>SL</Nombre>
		<Participantes>
			<Participante>
				<RefEntidad idref="_1" />
				<Cardinalidad min="1" max="1" />
			</Participante>
			<Participante>
				<RefEntidad idref="_5" />
				<Cardinalidad min="1" max="n" />
			</Participante>
		</Participantes>
	</Relacion>
	<Relacion id="_27" tipo="ASOCIACION">
		<Nombre>FO</Nombre>
		<Participantes>
			<Participante>
				<RefEntidad idref="_10" />
				<Cardinalidad min="0" max="n" />
			</Participante>
			<Participante>
				<RefEntidad idref="_19" />
				<Cardinalidad min="1" max="1" />
			</Participante>
		</Participantes>
	</Relacion>
	<Relacion id="_30" tipo="ASOCIACION">
		<Nombre>VtaLoc</Nombre>
		<Participantes>
			<Participante>
				<RefEntidad idref="_10" />
				<Cardinalidad min="0" max="n" />
			</Participante>
			<Participante>
				<RefEntidad idref="_1" />
				<Cardinalidad min="0" max="n" />
			</Participante>
		</Participantes>
		<Atributos>
			<Atributo id="_32" tipo="CARACTERIZACION">
				<Nombre>tarj</Nombre>
				<Cardinalidad min="0" max="1" />
				<Atributos>
					<Atributo id="_34" tipo="CARACTERIZACION">
						<Nombre>nomTarj</Nombre>
						<Cardinalidad min="1" max="1" />
					</Atributo>
					<Atributo id="_35" tipo="CARACTERIZACION">
						<Nombre>bco</Nombre>
						<Cardinalidad min="1" max="1" />
					</Atributo>
					<Atributo id="_36" tipo="CARACTERIZACION">
						<Nombre>nroTarj</Nombre>
						<Cardinalidad min="1" max="1" />
					</Atributo>
					<Atributo id="_37" tipo="CARACTERIZACION">
						<Nombre>nroAutoriz</Nombre>
						<Cardinalidad min="1" max="1" />
					</Atributo>
					<Atributo id="_38" tipo="CARACTERIZACION">
						<Nombre>cr</Nombre>
						<Cardinalidad min="0" max="1" />
						<Atributos>
							<Atributo id="_39" tipo="CARACTERIZACION">
								<Nombre>cuotas</Nombre>
								<Cardinalidad min="1" max="1" />
							</Atributo>
							<Atributo id="_40" tipo="CARACTERIZACION">
								<Nombre>int</Nombre>
								<Cardinalidad min="0" max="1" />
							</Atributo>
						</Atributos>
					</Atributo>
				</Atributos>
			</Atributo>
		</Atributos>
	</Relacion>
	<Diagrama id="_41">
		<Nombre>BoleteriaTeatro</Nombre>
		<Componentes>
			<Componente idref="_41" />
			<Componente idref="_41" />
			<Componente idref="_41" />
			<Componente idref="_41" />
			<Componente idref="_41" />
			<Componente idref="_41" />
			<Componente idref="_41" />
		</Componentes>
		<Validacion estado="SIN_VALIDAR">
			<Observaciones />
		</Validacion>
	</Diagrama>
	<!-- Estado global de los diagramas -->
	<Validacion estado="SIN_VALIDAR">
		<Observaciones />
	</Validacion>
</Modelo>
