=== jfacorro/2012-1er-taller-de-programacion-ii/trunk/MEREditor/xml/modelo-rep.dtd
<!ELEMENT Representaciones (Representacion+)>
<!ELEMENT Representacion (Posicion, Dimension)>
<!ELEMENT Posicion (#PCDATA)>
<!ELEMENT Dimension (#PCDATA)>

<!ATTLIST Representacion id ID #REQUIRED>
<!ATTLIST Posicion x CDATA #REQUIRED>
<!ATTLIST Posicion y CDATA #REQUIRED>
<!ATTLIST Dimension ancho CDATA #REQUIRED>
<!ATTLIST Dimension alto CDATA #REQUIRED>

=== jfacorro/2012-1er-taller-de-programacion-ii/trunk/MEREditor/xml/tests/representacion.xml
<!DOCTYPE note SYSTEM "../modelo-rep.dtd">
<Representaciones>
    <Representacion id="_1">
        <Posicion x="100" y="100" />
        <Dimension ancho="50" alto="40" />
    </Representacion>
    <Representacion id="_24">
        <Posicion x="150" y="150" />
        <Dimension ancho="100" alto="50" />
    </Representacion>
    <Representacion id="_27">
        <Posicion x="150" y="200" />
        <Dimension ancho="100" alto="50" />
    </Representacion>
    <Representacion id="_30">
        <Posicion x="150" y="250" />
        <Dimension ancho="100" alto="50" />
    </Representacion>
</Representaciones>
